### ISSUE TITLE
how to create a blank node without BASE URI, since in theory should not have URI

### ISSUE THREAD

**Issue by ranielli** [ruby-rdf/spira#36]
irb(main):029:0> teste = Address.for(RDF::Node.new)
=> <Address:44192720 @subject: _:g44192860>
irb(main):030:0> teste.save
ArgumentError: Cannot create identifier for Address by String without base_uri; an RDF::URI is required

**Comment by pmackay** [comment]
Is there any best practice how this should be handled? Would it make sense to create a random UUID to create a new unique URI?

**Comment by abrisse** [comment]
@pmackay : that's a good way yes.
