### ISSUE TITLE
Use of inefficient splat argument methods in Spira codebase

### ISSUE THREAD

**Issue by jperville** [ruby-rdf/spira#40]
As a follow-up to ruby-rdf/rdf#214, the spira codebase contains at least two use of splat argument method invoked with a potentially large number of statements:
 - https://github.com/ruby-rdf/spira/blob/459d49554a064bd05be9a3442774316ea53c1b87/lib/spira/utils.rb#L24
 - https://github.com/ruby-rdf/spira/blob/develop/lib/spira/persistence.rb#L463

These should be refactored to use `RDF::Writable#insertn` and `RDF::Writable#insertn`; the speedup on these (seldom invoked) utility methods should be quite noticeable.

**Comment by gkellogg** [comment]
Note that the Utils#rename! was never implemented properly. I've fixed that in a previous commit, which uses a transaction.
